apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kuberlogicservices.kuberlogic.com
spec:
  group: kuberlogic.com
  names:
    plural: kuberlogicservices
    singular: kuberlogicservice
    kind: KuberLogicService
    listKind: KuberLogicServiceList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: integer
            status:
              type: object
              properties:
                phase:
                  type: string
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: webhook-service
          path: /convert
        caBundle: "" # Provide the CA bundle here if necessary
      conversionReviewVersions:
        - v1
